### PR TITLE
[WIP]SN-53 registration activation link email

### PR DESCRIPTION
**Pull request by joannaswiatek**
Need some help to review the code, but hope most is done

### CODE REVIEW

**Review by theadzik — COMMENTED** [review]
I got an exception when trying to run the project.
```ImportError: cannot import name 'six' from 'django.utils' ```

Please update requirements.txt

**Comment by joannaswiatek** [comment]
reqiurements updated and import changed.

**Review by daniel-wozniak — APPROVED** [review]
Można mergować

**Review by daniel-wozniak — APPROVED** [review]
recenzja?

**Pull request merged**
